#include "tapdance_common.h"
#include "tapdance.h"
#include "macro_common.h"

qk_tap_dance_action_t tap_dance_actions[] = {
    /* Layer switch row */
    [TD_L0_P1]   = MY_TDLAYER_MOVE_ACTION(KC_1, KC_NO, 0),
    [TD_L0_CDN]  = MY_TDLAYER_MOVE_ACTION(C(KC_DOWN), KC_NO, 0),
    [TD_L0_SPC1] = MY_TDLAYER_MOVE_ACTION(EMACS_SPC_1, KC_NO, 0),
    [TD_L0_A]    = MY_TDLAYER_MOVE_ACTION(KC_A, KC_NO, 0),
    [TD_L0_I]    = MY_TDLAYER_MOVE_ACTION(KC_I, KC_NO, 0),

    [TD_L2_P2]   = MY_TDLAYER_MOVE_ACTION(KC_2, KC_NO, 2),
    [TD_L2_SWDN_SWRGHT] = MY_TDLAYER_MOVE_ACTION(SWIN(KC_DOWN), SWIN(KC_RGHT), 2),
    [TD_L2_SPC2] = MY_TDLAYER_MOVE_ACTION(EMACS_SPC_2, KC_NO, 2),
    [TD_L2_B]    = MY_TDLAYER_MOVE_ACTION(KC_B, KC_NO, 2),
    [TD_L2_J]    = MY_TDLAYER_MOVE_ACTION(KC_J, KC_NO, 2),

    [TD_L3_P3]   = MY_TDLAYER_MOVE_ACTION(KC_3, KC_NO, 3),
    [TD_L3_PGDN] = MY_TDLAYER_MOVE_ACTION(KC_PGDN, KC_NO, 3),
    [TD_L3_SPC3] = MY_TDLAYER_MOVE_ACTION(EMACS_SPC_3, KC_NO, 3),
    [TD_L3_C]    = MY_TDLAYER_MOVE_ACTION(KC_C, KC_NO, 3),
    [TD_L3_K]    = MY_TDLAYER_MOVE_ACTION(KC_K, KC_NO, 3),

    [TD_L4_PMNS] = MY_TDLAYER_MOVE_ACTION(KC_MINS, KC_NO, 4),
    [TD_L4_CW]   = MY_TDLAYER_MOVE_ACTION(C(KC_W), KC_NO, 4),
    [TD_L4_SPC4] = MY_TDLAYER_MOVE_ACTION(EMACS_SPC_4, KC_NO, 4),
    [TD_L4_D]    = MY_TDLAYER_MOVE_ACTION(KC_D, KC_NO, 4),
    [TD_L4_L]    = MY_TDLAYER_MOVE_ACTION(KC_L, KC_NO, 4),

    /* Numpad */
    [TD_PSLS_NLCK] = MY_TD_ACTION(KC_SLSH, KC_NO, KC_ENT),
    [TD_PLUS_EQL]  = MY_TD_ACTION(KC_PLUS, KC_NO, KC_EQL),
    [TD_PAST_PERC] = MY_TD_ACTION(KC_ASTR, KC_NO, KC_PERC),
    [TD_ENT_ESC]   = MY_TD_ACTION(KC_ENT, KC_NO, KC_ESC),

    /* Utility */
    [TD_FOX_PC] = MY_TD_ACTION(MY_PASS_PC, KC_NO, MY_EMAIL_FOX),
    [TD_GOOGLES] = MY_TD_ACTION(MY_PASS_GOOGLE, KC_NO, MY_EMAIL_GOOGLE),
    [TD_PRIVATE_ROUTER] = MY_TD_ACTION(MY_PASS_ROUTER, KC_NO, MY_EMAIL_PRIVATE),
    [TD_WORK_BITWARDEN] = MY_TD_ACTION(MY_PASS_BITWARDEN, KC_NO, MY_EMAIL_WORK),

    /* Navigation */
    [TD_CR_CK_CW] = MY_TD_ACTION(C(KC_R), C(KC_K), C(KC_W)),
    [TD_CPGUP_MBTN4] = MY_TD_ACTION(C(KC_PGUP), KC_NO, KC_MS_BTN4),
    [TD_CPGDN_MBTN5] = MY_TD_ACTION(C(KC_PGDN), KC_NO, KC_MS_BTN5),
    [TD_SWUP_SWLEFT] = MY_TD_ACTION(SWIN(KC_UP), KC_NO, SWIN(KC_LEFT)),
    [TD_LWIN_ESC] = MY_TD_ACTION(KC_LWIN, KC_NO, KC_ESC),
    [TD_ZOOM_BROWER] = MY_TD_ACTION(C(KC_EQL), KC_NO, C(KC_MINS))
};
