#include "tapdance.h"

qk_tap_dance_action_t tap_dance_actions[] = {
    [TD_PLUS_NUMLCK] = ACTION_TAP_DANCE_DOUBLE(KC_PSLS, KC_NLCK),
    [TD_PLUS_EQL]    = ACTION_TAP_DANCE_DOUBLE(KC_PPLS, KC_EQL),
    [TD_PAST_TG2]    = ACTION_TAP_DANCE_LAYER_TOGGLE(KC_PAST, 2),
    [TD_PMNS_TG3]    = ACTION_TAP_DANCE_LAYER_TOGGLE(KC_PMNS, 3),
    [TD_PDOT_TO2]    = ACTION_TAP_DANCE_LAYER_MOVE(KC_PDOT, 2),
    [TD_BSPC_TO3]    = ACTION_TAP_DANCE_LAYER_MOVE(KC_BSPC, 3),
};
